### ISSUE TITLE
Add Docker files for easier development/deployment

### ISSUE THREAD

**Issue by nucleardreamer** [colejoffray/Stockify#4]
One common thing for a database driven project is the run `mongodb` and your project inside Docker (see [installing here](https://docs.docker.com/desktop/install/mac-install/)). In the situation this will be two files, one `Dockerfile` and one `docker-compose.yml`.  This gives you portability for the database (meaning it's not just installed locally), and replicates what you might deploy to a service like [railway](https://railway.app/), heroku, etc.

A simple `Dockerfile` would be something like:

```
FROM node:18-slim

COPY package*.json ./

RUN JOBS=MAX npm install --production && npm cache verify && rm -rf /tmp/*

COPY . ./

CMD ["npm", "start"]
```

And a `docker-compose.yml` something like this:

```
version: "2.1"

services:
  stockify:
    container_name: stockify
    build: .
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
```

Note, this is just an example from memory and not tested, so it may not work right off the bat. Let's chat if you want to learn more about Docker!
